package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"graphql-go/auth"
	"graphql-go/core/schedule"
	"graphql-go/core/stats"
	"graphql-go/graph/model"
	"graphql-go/persistence"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Author is the resolver for the author field.
func (r *burgerDayResolver) Author(ctx context.Context, obj *model.BurgerDay) (*model.User, error) {
	// Batch-loaded by hydrateBurgerDays when this day came from a list resolver.
	if obj.Author != nil {
		return obj.Author, nil
	}

	user := &persistence.User{ID: obj.AuthorId}
	res := r.DB.First(user)
	if res.Error != nil {
		return nil, res.Error // It's better to return the error rather than panic, to handle it gracefully
	}

	// Assuming persistence.UserToModel converts a persistence.User to a *model.User
	return persistence.UserToModel(user), nil
}

// Orders is the resolver for the orders field.
func (r *burgerDayResolver) Orders(ctx context.Context, obj *model.BurgerDay) ([]*model.Order, error) {
	var orders []*persistence.Order

	res := r.DB.Where("burger_day_id = ?", obj.ID).Find(&orders)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.OrdersToModels(orders), nil
}

// OrdersCount is the resolver for the ordersCount field.
func (r *burgerDayResolver) OrdersCount(ctx context.Context, obj *model.BurgerDay) (int, error) {
	// Batch-loaded by hydrateBurgerDays when this day came from a list resolver.
	if obj.OrdersCountCache != nil {
		return *obj.OrdersCountCache, nil
	}

	var count int64
	err := r.DB.Model(&persistence.Order{}).Where("burger_day_id = ?", obj.ID).Count(&count).Error
	if err != nil {
		return 0, err
	}
	return int(count), nil
}

// Weekday is the resolver for the weekday field.
func (r *burgerDayResolver) Weekday(ctx context.Context, obj *model.BurgerDay) (int, error) {
	return schedule.Weekday(obj.Date), nil
}

// OffSchedule is the resolver for the offSchedule field.
func (r *burgerDayResolver) OffSchedule(ctx context.Context, obj *model.BurgerDay) (bool, error) {
	return schedule.IsOffSchedule(obj.Date), nil
}

// CloseBurgerDay is the resolver for the close_burger_day field.
func (r *mutationResolver) CloseBurgerDay(ctx context.Context, burgerDayID string) (*model.BurgerDay, error) {
	burgerDay := &persistence.BurgerDay{ID: burgerDayID}
	res := r.DB.First(burgerDay)

	if res.Error != nil {
		return nil, res.Error
	}

	burgerDay.Closed = true
	res = r.DB.Save(burgerDay)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(burgerDay), nil
}

// CreateUser is the resolver for the create_user field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	user := &persistence.User{
		ID:    uuid.New().String(),
		Name:  name,
		Email: email,
	}

	res := r.DB.Create(user)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.UserToModel(user), nil
}

// OrderBurger is the resolver for the orderBurger field.
func (r *mutationResolver) OrderBurger(ctx context.Context, burgerDayID string, specialRequest []model.SpecialOrders) (*model.Order, error) {
	user := auth.ForContext(ctx)
	order := &persistence.Order{
		ID:             uuid.New().String(),
		UserId:         user.ID,
		BurgerDayId:    burgerDayID,
		SpecialRequest: persistence.SpecialOrdersToStrings(specialRequest),
	}
	burgerDay := &persistence.BurgerDay{ID: burgerDayID}
	r.DB.First(burgerDay)
	if burgerDay.Closed {
		return nil, stats.ErrBurgerDayClosed{}
	}

	res := r.DB.Create(order)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.OrderToModel(order), nil
}

// PayOrder is the resolver for the pay_order field.
// The userID argument is a legacy parameter and is deliberately ignored; the order is
// looked up by its own id. It is kept so existing clients keep working unchanged.
func (r *mutationResolver) PayOrder(ctx context.Context, orderID string, userID string) (*model.Order, error) {
	order := &persistence.Order{ID: orderID}
	res := r.DB.First(order)

	if res.Error != nil {
		return nil, res.Error
	}

	order.Paid = !order.Paid

	res = r.DB.Save(order)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.OrderToModel(order), nil
}

// RingBurgerBell is the resolver for the ringBurgerBell field.
func (r *mutationResolver) RingBurgerBell(ctx context.Context, message string) (bool, error) {
	// Create a new BurgerBellEvent with the message and current timestamp
	event := &model.BurgerBellEvent{
		Message:   message,
		Timestamp: time.Now().Format(time.RFC3339),
	}

	// Use PublishBurgerBellEvent to send the event to all subscribers
	r.PublishBurgerBellEvent(event)
	return true, nil
}

// StartBurgerDay is the resolver for the start_burger_day field.
func (r *mutationResolver) StartBurgerDay(ctx context.Context) (*model.BurgerDay, error) {
	user := auth.ForContext(ctx)
	currentDateString := time.Now().Format("2006-01-02") // Format the date as a string in the format "YYYY-MM-DD"

	burgerDay := &persistence.BurgerDay{
		ID:       uuid.New().String(),
		AuthorId: user.ID,
		Date:     currentDateString, // Set the date to the current date
	}

	res := r.DB.Create(burgerDay)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(burgerDay), nil
}

// UpdateBurgerDay is the resolver for the update_burger_day field.
func (r *mutationResolver) UpdateBurgerDay(ctx context.Context, burgerDayID string, estimatedTime *string, price *float64, closed *bool) (*model.BurgerDay, error) {
	burgerDay := &persistence.BurgerDay{ID: burgerDayID}
	res := r.DB.First(burgerDay)
	if res.Error != nil {
		return nil, res.Error
	}

	if estimatedTime != nil {
		burgerDay.EstimatedTime = *estimatedTime
	}
	if price != nil {
		burgerDay.Price = *price
	}
	if closed != nil {
		burgerDay.Closed = *closed
	}

	res = r.DB.Save(burgerDay)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(burgerDay), nil
}

// UpdateUser is the resolver for the update_user field.
func (r *mutationResolver) UpdateUser(ctx context.Context, name *string, email *string, phoneNumber *string) (*model.User, error) {
	userCtx := auth.ForContext(ctx)
	user := &persistence.User{ID: userCtx.ID}

	res := r.DB.First(user)
	if res.Error != nil {
		return nil, res.Error
	}

	if name != nil {
		user.Name = *name
	}
	if email != nil {
		user.Email = *email
	}
	if phoneNumber != nil {
		user.PhoneNumber = *phoneNumber
	}

	res = r.DB.Save(user)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.UserToModel(user), nil
}

// DeleteBurgerDay is the resolver for the delete_burger_day field.
// Kept for backwards compatibility: the return type stays a nullable String and a
// refusal is still thrown. New clients should use delete_burger_days, which reports
// refusals as data. Unlike before, the day's orders are removed with it.
func (r *mutationResolver) DeleteBurgerDay(ctx context.Context, burgerDayID string) (*string, error) {
	result := deleteBurgerDay(r.DB, auth.ForContext(ctx), burgerDayID)
	if !result.Deleted {
		return nil, errors.New(*result.Error)
	}

	return &burgerDayID, nil
}

// DeleteBurgerDays is the resolver for the delete_burger_days field.
func (r *mutationResolver) DeleteBurgerDays(ctx context.Context, burgerDayIds []string) ([]*model.DeleteBurgerDayResult, error) {
	if len(burgerDayIds) > maxBulkDeleteBurgerDays {
		return nil, fmt.Errorf("cannot delete more than %d burger days in one call, got %d", maxBulkDeleteBurgerDays, len(burgerDayIds))
	}

	user := auth.ForContext(ctx)

	// One result per requested id, in request order, even for duplicate ids: a refused
	// or missing id must never fail the rest of the call.
	results := make([]*model.DeleteBurgerDayResult, len(burgerDayIds))
	for i, burgerDayID := range burgerDayIds {
		results[i] = deleteBurgerDay(r.DB, user, burgerDayID)
	}

	return results, nil
}

// DeleteBurger is the resolver for the deleteBurger mutation.
// Only the owner of the burger day can delete ses
func (r *mutationResolver) DeleteOrder(ctx context.Context, orderID string) (bool, error) {
	userCtx := auth.ForContext(ctx)

	var order persistence.Order
	if err := r.DB.First(&order, "id = ?", orderID).Error; err != nil {
		return false, err
	}

	var burgerDay persistence.BurgerDay
	if err := r.DB.First(&burgerDay, "id = ?", order.BurgerDayId).Error; err != nil {
		return false, err
	}

	// Check if the logged-in user is the author of the burger day
	if burgerDay.AuthorId != userCtx.ID {
		return false, errors.New("only the owner of the burger day can delete orders")
	}

	// Delete the order
	if err := r.DB.Delete(&order).Error; err != nil {
		return false, err
	}

	return true, nil
}

// ConsolidateEmails is the resolver for the consolidate_emails field.
// Merges accounts with the same name into the current user's account.
func (r *mutationResolver) ConsolidateEmails(ctx context.Context) (bool, error) {
	user := auth.ForContext(ctx)

	// Find users to merge - must have exact matching name
	var usersToMerge []persistence.User
	if err := r.DB.Where("name = ? AND id != ?", user.Name, user.ID).Find(&usersToMerge).Error; err != nil {
		return false, err
	}

	if len(usersToMerge) == 0 {
		return true, nil
	}

	// Use transaction for data integrity
	err := r.DB.Transaction(func(tx *gorm.DB) error {
		for _, oldUser := range usersToMerge {
			// Reassign all orders from old user to current user
			if err := tx.Model(&persistence.Order{}).Where("user_id = ?", oldUser.ID).Update("user_id", user.ID).Error; err != nil {
				return err
			}

			// Reassign all burger days from old user to current user
			if err := tx.Model(&persistence.BurgerDay{}).Where("author_id = ?", oldUser.ID).Update("author_id", user.ID).Error; err != nil {
				return err
			}

			// Delete the old user
			if err := tx.Delete(&oldUser).Error; err != nil {
				return err
			}
		}
		return nil
	})

	if err != nil {
		return false, err
	}

	return true, nil
}

// BurgerDay is the resolver for the burgerDay field.
func (r *orderResolver) BurgerDay(ctx context.Context, obj *model.Order) (*model.BurgerDay, error) {
	burgerDay := &persistence.BurgerDay{ID: obj.BurgerDayId}
	res := r.DB.First(burgerDay)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(burgerDay), nil
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	user := &persistence.User{ID: obj.UserId}
	res := r.DB.First(user)
	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.UserToModel(user), nil
}

// AccumulatedOrders is the resolver for the accumulated_orders field.
func (r *queryResolver) AccumulatedOrders(ctx context.Context) (*model.AccumulatedOrders, error) {
	bg_day, error := current_burger_day(r.DB)

	if error != nil {
		return nil, error
	}
	if bg_day == nil {
		return nil, nil
	}
	var orders []*persistence.Order
	if err := r.DB.Where("burger_day_id = ?", bg_day.ID).Find(&orders).Error; err != nil {
		return nil, err
	}

	// Map to count unique special order combinations
	uniqueOrders := make(map[string]int)
	for _, order := range orders {
		key := strings.Join(order.SpecialRequest, ",")
		uniqueOrders[key]++
	}

	// Convert to AccumulatedOrderLine slice
	var accumulatedOrderLines []*model.AccumulatedOrderLine
	for specialReq, count := range uniqueOrders {
		specialOrders, err := persistence.StringsToSpecialOrders(strings.Split(specialReq, ","))
		if err != nil {
			return nil, err
		}
		accumulatedOrderLines = append(accumulatedOrderLines, &model.AccumulatedOrderLine{
			Amount:         count,
			SpecialRequest: specialOrders,
		})
	}

	return &model.AccumulatedOrders{
		ID:      bg_day.ID,
		Count:   len(orders),
		ToOrder: accumulatedOrderLines,
	}, nil
}

// BurgerDay is the resolver for the burger_day field.
func (r *queryResolver) BurgerDay(ctx context.Context, id string) (*model.BurgerDay, error) {
	burgerDay := persistence.BurgerDay{}
	res := r.DB.First(&burgerDay, id)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(&burgerDay), nil
}

// BurgerDays is the resolver for the burger_days field.
func (r *queryResolver) BurgerDays(ctx context.Context, offScheduleOnly *bool) ([]*model.BurgerDay, error) {
	var burgerDays []*persistence.BurgerDay
	res := r.DB.Order("date asc").Find(&burgerDays)

	if res.Error != nil {
		return nil, res.Error
	}

	days := persistence.BurgerDaysToModels(burgerDays)

	if offScheduleOnly != nil && *offScheduleOnly {
		offSchedule := make([]*model.BurgerDay, 0, len(days))
		for _, day := range days {
			if schedule.IsOffSchedule(day.Date) {
				offSchedule = append(offSchedule, day)
			}
		}
		days = offSchedule
	}

	// Resolve author and ordersCount for every day up front, so the per-field
	// resolvers do not issue one query per row.
	if err := hydrateBurgerDays(r.DB, days); err != nil {
		return nil, err
	}

	return days, nil
}

// BurgerStats is the resolver for the burgerStats field.
func (r *queryResolver) BurgerStats(ctx context.Context, includeOffSchedule *bool) (*model.BurgerStats, error) {
	var excludedDayIDs []string
	if includeOffSchedule != nil && !*includeOffSchedule {
		var err error
		if excludedDayIDs, err = offScheduleBurgerDayIDs(r.DB); err != nil {
			return nil, err
		}
	}

	res, err := stats.CalculateBurgerStats(r.DB, excludedDayIDs)
	if err != nil {
		return nil, err
	}

	return stats.BurgerStatsToModel(res), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	order := persistence.Order{}
	res := r.DB.First(&order, id)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.OrderToModel(&order), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	var orders []*persistence.Order

	// preload user on order
	res := r.DB.Find(&orders)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.OrdersToModels(orders), nil
}

// TodaysBurgers is the resolver for the todays_burgers field.
func (r *queryResolver) TodaysBurgers(ctx context.Context) (*model.BurgerDay, error) {
	currentDateString := time.Now().Format("2006-01-02") // Format the date as a string in the format "YYYY-MM-DD"
	burgerDay := &persistence.BurgerDay{}
	res := r.DB.Where("date = ?", currentDateString).First(burgerDay)
	if res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, nil // Return nil if no record is found for today
		}
		return nil, res.Error
	}

	return persistence.BurgerDayToModel(burgerDay), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user := persistence.User{ID: id}
	res := r.DB.First(&user)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.UserToModel(&user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	var users []*persistence.User
	res := r.DB.Find(&users)

	if res.Error != nil {
		return nil, res.Error
	}

	return persistence.UsersToModels(users), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := auth.ForContext(ctx)
	return persistence.UserToModel(user), nil
}

// CheckEmail is the resolver for the check_email field.
// Returns emails of other users with the exact same name (potential duplicates from AD changes).
func (r *queryResolver) CheckEmail(ctx context.Context) ([]string, error) {
	user := auth.ForContext(ctx)

	var duplicateUsers []persistence.User
	if err := r.DB.Where("name = ? AND id != ?", user.Name, user.ID).Find(&duplicateUsers).Error; err != nil {
		return nil, err
	}

	emails := make([]string, len(duplicateUsers))
	for i, u := range duplicateUsers {
		emails[i] = u.Email
	}

	return emails, nil
}

// BurgerBell is the resolver for the burgerBell field.
func (r *subscriptionResolver) BurgerBell(ctx context.Context) (<-chan *model.BurgerBellEvent, error) {
	// Register a new subscriber and get a unique channel
	id, ch := r.RegisterSubscriber()

	// Set up cleanup when the context is done
	go func() {
		<-ctx.Done()
		r.UnregisterSubscriber(id)
	}()

	return ch, nil
}

// IsAdmin is the resolver for the isAdmin field.
func (r *userResolver) IsAdmin(ctx context.Context, obj *model.User) (bool, error) {
	return auth.IsAdmin(obj.Email), nil
}

// BurgerDay returns BurgerDayResolver implementation.
func (r *Resolver) BurgerDay() BurgerDayResolver { return &burgerDayResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	burgerDayResolver    struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	orderResolver        struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
	userResolver         struct{ *Resolver }
)
